# Generated by Django 4.1.7 on 2023-03-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='credit_card_number',
            field=models.CharField(max_length=16),
        ),
    ]
