# Generated by Django 4.1.7 on 2023-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_description',
            field=models.CharField(blank=True, default='Company Description...', max_length=300, null=True),
        ),
    ]
