# Generated by Django 4.1.7 on 2023-03-14 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_company_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='companies',
        ),
        migrations.AddField(
            model_name='product',
            name='companies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
