# Generated by Django 4.1.7 on 2023-03-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_company_product_remove_product_companies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_description',
            field=models.TextField(blank=True, default='Company Description...', max_length=300, null=True),
        ),
    ]
